os: linux

node_js:
  - 12

language: scala

jdk:
  - oraclejdk11

scala:
  - 2.12.11
  - 2.13.4

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

#before_cache:
#  # Tricks to avoid unnecessary cache updates
#  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
#  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
#  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
#  - find $HOME/.sbt -name "*.lock" -delete

cache:
  yarn: true
# @TODO cache is causing this Travis error for some reason: [error] [launcher] could not retrieve Scala 2.12.10: missing scala.Option
#  directories:
#    - $HOME/.ivy2/cache
#    - $HOME/.sbt
#    - $HOME/.coursier
#    - $HOME/.cache/coursier/v1
